-- MySQL Script generated by MySQL Workbench
-- Wed Apr 20 13:44:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema magazijn
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `magazijn` ;

-- -----------------------------------------------------
-- Schema magazijn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `magazijn` DEFAULT CHARACTER SET utf8 ;
USE `magazijn` ;

-- -----------------------------------------------------
-- Table `magazijn`.`Persoon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magazijn`.`Persoon` (
  `Id` INT NOT NULL,
  `Voornaam` VARCHAR(45) NOT NULL,
  `Tussenvoegsels` VARCHAR(45) NOT NULL,
  `Achternaam` VARCHAR(45) NOT NULL,
  `Email` INT NOT NULL,
  `StudentId` INT NOT NULL,
  PRIMARY KEY (`Id`, `StudentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magazijn`.`Docent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magazijn`.`Docent` (
  `Id` INT NOT NULL,
  `Docentafkorting` VARCHAR(45) NOT NULL,
  `Voornaam` VARCHAR(45) NOT NULL,
  `Tussenvoegsel` VARCHAR(45) NULL,
  `Achternaam` VARCHAR(45) NOT NULL,
  `Klas` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `telefoonnummer` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magazijn`.`klas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magazijn`.`klas` (
  `klas` VARCHAR(45) NOT NULL,
  `mentor` INT NOT NULL,
  PRIMARY KEY (`klas`),
  INDEX `mentorklas_idx` (`mentor` ASC) ,
  CONSTRAINT `mentorklas`
    FOREIGN KEY (`mentor`)
    REFERENCES `magazijn`.`Docent` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
