-- MySQL Script generated by MySQL Workbench
-- Tue Apr  5 14:54:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema magazijn
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oefenkerntaakexamen1` ;

-- -----------------------------------------------------
-- Schema magazijn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oefenkerntaakexamen1` DEFAULT CHARACTER SET utf8 ;
USE `magazijn` ;

-- -----------------------------------------------------
-- Table `oefenkerntaakexamen1`.`Afdeling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oefenkerntaakexamen1`.`Afdeling` (
  `Id` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oefenkerntaakexamen1`.`Magazijn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oefenkerntaakexamen1`.`Magazijn` (
  `Id` INT NOT NULL,
  `AfdelingId` INT NULL,
  `Magazijncol` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_Afdeling_Magazijn_idx` (`AfdelingId` ASC) ,
  CONSTRAINT `FK_Afdeling_Magazijn`
    FOREIGN KEY (`AfdelingId`)
    REFERENCES `oefenkerntaakexamen1`.`Afdeling` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oefenkerntaakexamen1`.`Catogorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oefenkerntaakexamen1`.`Catogorie` (
  `Id` INT NOT NULL,
  `Catogorienaam` VARCHAR(45) NOT NULL,
  `Catogoriecode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oefenkerntaakexamen1`.`Artikel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oefenkerntaakexamen1`.`Artikel` (
  `Id` INT NOT NULL,
  `Omschrijving` VARCHAR(45) NOT NULL,
  `AantalInBeschikking` INT NOT NULL,
  `AantalInLeen` INT NOT NULL,
  `CatogorieId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_Catogorie_Artikel_idx` (`CatogorieId` ASC) ,
  CONSTRAINT `FK_Catogorie_Artikel`
    FOREIGN KEY (`CatogorieId`)
    REFERENCES `oefenkerntaakexamen1`.`Catogorie` (`Id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oefenkerntaakexamen1`.`MagazijnArtikel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oefenkerntaakexamen1`.`MagazijnArtikel` (
  `MagazijnId` INT NOT NULL,
  `CatogorieId` INT NOT NULL,
  PRIMARY KEY (`MagazijnId`, `CatogorieId`),
  INDEX `fk_magazijn_artikel_idx` (`MagazijnId` ASC) ,
  INDEX `fk_magazijnartikel_catogorie_idx` (`CatogorieId` ASC) ,
  CONSTRAINT `fk_magazijn_artikel`
    FOREIGN KEY (`MagazijnId`)
    REFERENCES `oefenkerntaakexamen1`.`oefenkerntaakexamen1` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_magazijnartikel_catogorie`
    FOREIGN KEY (`CatogorieId`)
    REFERENCES `oefenkerntaakexamen1`.`Catogorie` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oefenkerntaakexamen1`.`Persoon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magazijn`.`Persoon` (
  `Id` INT NOT NULL,
  `Naam` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oefenkerntaakexamen1`.`Aanvraag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oefenkerntaakexamen1`.`Aanvraag` (
  `Id` INT NOT NULL,
  `MagazijnArtikelId` INT NOT NULL,
  `Aantal` INT NOT NULL,
  `PersoonId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_AanvraagPersoon_idx` (`PersoonId` ASC) ,
  INDEX `FK_AanvraagMagazijnArtikel_idx` (`MagazijnArtikelId` ASC) ,
  CONSTRAINT `FK_AanvraagPersoon`
    FOREIGN KEY (`PersoonId`)
    REFERENCES `oefenkerntaakexamen1`.`Persoon` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AanvraagMagazijnArtikel`
    FOREIGN KEY (`MagazijnArtikelId`)
    REFERENCES `oefenkerntaakexamen1`.`MagazijnArtikel` (`MagazijnId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
